[package]
name = "dominant-colours"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
image = "0.24"
linfa = "0.7"
linfa-clustering = "0.7"
ndarray = "0.15"
